name: githubexplore
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  http: ^1.2.0
  flutter_native_splash: ^2.3.11
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.5
  connectivity_plus: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#d5bbed"
  image: assets/images/github.png
  android_12:
    image: assets/images/github.png
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/no_data1.jpg
    - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
